### PR TITLE
adding ntpd support to busybox, since rdate does not work on some networks

### PR DESCRIPTION
**Pull request by oasenov**
ntpd in busybox

### CODE REVIEW

**Comment by msieben** [comment]
Thanks for reporting. It is an issue that has been around for some time and sporadically surfaces. The script fired by the if-up hook (see package/skeleton) may start too early. rdate, then, fails to resolve the addresses because dhcp (dns) settings have not yet been set. In this situation settings are applied after the script has finished execution, not during, but then it is too late. Since the script is blocking and no updates can be processes while it executes, any delay added to the start does not resolve the issue either. Basically, it is race condition between dhcp and the hook. A solution could be to start the rdate script in the background by another hook or to daemonize it.

**Comment by rybon** [comment]
> A solution could be to start the rdate script in the background by another hook or to daemonize it.

Will this solution be available anytime soon? Can `rdate` be replaced by `ntp`? I can't find any public time server still responding to `rdate` calls, it seems it was deprecated a long time ago.

**Comment by oasenov** [comment]
actually i just wanted to have ntpd  available on rpi build, for developers, system integrators. it makes some people's life easier :)

**Comment by hlev** [comment]
Just in case anyone wanders over here. A list of time servers that support the old time protocol `rdate` uses (some of these are also configured as default in `BR2_TARGET_GENERIC_TIMESERVER`): http://tf.nist.gov/tf-cgi/servers.cgi

**Comment by albertd** [comment]
WPE Framework has been added now which correctly handles ntp

**Pull request closed without merging**
